spring.datasource.url=jdbc:h2:file:./data/sbommaker;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.thymeleaf.cache=false
app.name=SBOM Maker
app.logo-url=/images/logo.svg
app.api-key=change-me-in-production
server.port=6565
server.ssl.enabled=true
server.ssl.certificate=file:./ssl/server.crt
server.ssl.certificate-private-key=file:./ssl/server.key
